language: php
php:
  - "5.5"
  - "5.4"
install:
  - composer install
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "projectbase"
  on:
    branch: master